"""Typing stubs for the compiled `_bitalino_core` extension.

These stubs mirror the Rust implementation shipped as ``_bitalino_core``. The
extension is built via PyO3/abi3 and exported under ``bitalino_rs._bitalino_core``.
"""

DEFAULT_SAMPLING_RATE: int
VALID_SAMPLING_RATES: list[int]

class Frame:
    sequence: int
    digital: list[int]
    analog: list[int]
    def __init__(self, sequence: int, digital: list[int], analog: list[int]): ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def to_dict(self) -> dict: ...
    @property
    def n_channels(self) -> int: ...

class FrameBatch:
    frames: list[Frame]
    timestamp_us: int
    crc_errors: int
    sequence_gaps: int
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    @property
    def has_errors(self) -> bool: ...

class DeviceState:
    analog: list[int]
    battery: int
    battery_threshold: int
    digital: list[int]
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict: ...
    @property
    def battery_voltage(self) -> float: ...
    @property
    def is_battery_low(self) -> bool: ...

class Bitalino:
    sampling_rate: int
    def __init__(self, path: str): ...
    @staticmethod
    def connect(mac: str, pin: str = "1234") -> Bitalino: ...
    def version(self) -> str: ...
    def start(self, rate: int = 1000, channels: list[int] | None = None) -> None: ...
    def stop(self) -> None: ...
    def read(self, n_frames: int = 100) -> list[Frame]: ...
    def read_timed(self, n_frames: int = 100) -> FrameBatch: ...
    def set_battery_threshold(self, threshold: int = 30) -> None: ...
    def battery(self, value: int = 30) -> None: ...
    def state(self) -> DeviceState: ...
    def trigger(self, outputs: list[int] | None = None) -> None: ...
    def pwm(self, value: int = 100) -> None: ...
    @property
    def is_bitalino2(self) -> bool: ...
    @property
    def elapsed_us(self) -> int | None: ...

# Logging helpers

def enable_rust_logs(level: str | None = None) -> None: ...
def reset_log_cache() -> None: ...
